version: '3.8'

services:
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php
    depends_on:
      - db
    links:
      - db
    volumes:
      - ../src:/app
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      REDIS_HOST: ${REDIS_HOST}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - '${PROJECT_HOST}:80:80'
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../src:/app

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '${PROJECT_HOST}:${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  siege:
    container_name: ${PROJECT_NAME}_siege
    build:
      context: ./siege
    volumes:
      - ./siege:/work

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${PROJECT_HOST}:6379:6379

volumes:
  db-data: { }
